### ISSUE TITLE
Alternative hover effect #1

### ISSUE THREAD

**Issue by nightmono** [nightmono/nightmono.github.io#3]
Simple underline with variable thickness. An advantage it has over text-decoration underline is that it has a transition.

```css
a {
    text-decoration: none;
    font-weight: bold;
    white-space: nowrap;
    box-shadow: 0 .25ch var(--gre);
    color: var(--gre);
    transition: box-shadow .25s;
}

a:hover {
    box-shadow: none;
}
```
