### ISSUE TITLE
 Alternative hover effect #2

### ISSUE THREAD

**Issue by nightmono** [nightmono/nightmono.github.io#4]
Underline using text-decoration. Still has expanding padding, but only by half a character (1 char total) to reduce wrapping issues. _Note: wrapping issues can still occur, just less common now._

```css
a {
    font-weight: bold;
    white-space: nowrap;
    color: var(--gre);
    text-decoration: solid underline var(--gre) 2px;
    transition: color .25s, background-color .25s, padding .25s;
}

a:hover {
    padding: .25ch .5ch;
    color: var(--bg) !important; 
    background-color: var(--gre);
}
```
